# This pod will be used to manage the artifacts in the mounted location.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mi-deployment
  namespace: wso2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-mi-deployment
  template:
    metadata:
      labels:
        app: backend-mi-deployment
    spec:
      containers:
        - name: wso2mi
          #image: virajhasith/wso2mi-4.1.0:latest
          #image: virajhasith/wso2mi-4.1.0:randomPayload
          image: vikumkbv/miwithcertsandapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8290
              protocol: "TCP"
            - containerPort: 8253
              protocol: "TCP"
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8290
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8290
            timeoutSeconds: 30
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "2"
              memory: 2Gi