apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netstat-captured-data-storage-claim
  namespace: wso2
  labels:
    deployment: wso2am-pattern-1-am
    product: api-manager
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: netstat-captured-data-storage