
apiVersion: v1
kind: Service
metadata:
  name: wso2am-pattern-1-am-gateway-service
  namespace: wso2
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: wso2am-pattern-1-am
    product: api-manager
  ports:
    # ports that this service should serve on
    -
      name: pass-through-http
      protocol: TCP
      port: 8280
      targetPort: 8280
    -
      name: pass-through-https
      protocol: TCP
      port: 8243
      targetPort: 8243

    - name: websocket-ws
      protocol: TCP
      port: 9099
      targetPort: 9099

    - name: websocket-wss
      protocol: TCP
      port: 8099
      targetPort: 8099