apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2apim-log-storage-claim
  namespace: wso2
  labels:
    deployment: wso2am-pattern-1-am
    product: api-manager
spec:
  storageClassName: oci-fss
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
