
apiVersion: v1
kind: Service
metadata:
  name: wso2am-pattern-1-am-pubsub-service
  namespace: wso2
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: wso2am-pattern-1-am
    product: api-manager
  type: NodePort
  ports:
    # ports that this service should serve on
    -
      name: servlet-http
      protocol: TCP
      port: 9763
      targetPort: 9763
    -
      name: servlet-https
      protocol: TCP
      port: 9443
      targetPort: 9443

